----------------------
-- BORRADO DE VISTAS--
----------------------

DROP VIEW GR21_VISTA_MEJORES_CLIENTES;
DROP VIEW GR21_VISTA_POSICIONES;


-------------------------------------------------------
-- BORRADO DE FUNCIONES Y SUS DEPENDENCIAS (TRIGGERS)--
-------------------------------------------------------

DROP FUNCTION IF EXISTS FN_GR21_POSICIONES_LIBRES( date )CASCADE;
DROP FUNCTION IF EXISTS FN_GR21_POSICIONES_OCUPADAS_CLIENTE(integer) CASCADE;
/*DROP FUNCTION IF EXISTS TRFN_GR21_CONTROL_PESO_MAXIMO_FILA CASCADE;*/

--------------------------------------------
-- BORRADO DE LOS REGISTROS DE LAS TABLAS --
--------------------------------------------

DELETE FROM GR21_ALQUILER;
DELETE FROM GR21_ALQUILER_POSICIONES;
DELETE FROM GR21_CLIENTE;
DELETE FROM GR21_ESTANTERIA;
DELETE FROM GR21_FILA;
DELETE FROM GR21_MOVIMIENTO;
DELETE FROM GR21_MOV_ENTRADA;
DELETE FROM GR21_MOV_INTERNO;
DELETE FROM GR21_MOV_SALIDA;
DELETE FROM GR21_PALLET;
DELETE FROM GR21_POSICION;

---------------------------s
-- BORRADO DE LAS TABLAS --
---------------------------

DROP TABLE GR21_ALQUILER;
DROP TABLE GR21_ALQUILER_POSICIONES;
DROP TABLE GR21_CLIENTE;
DROP TABLE GR21_ESTANTERIA;
DROP TABLE GR21_FILA;
DROP TABLE GR21_MOVIMIENTO;
DROP TABLE GR21_MOV_ENTRADA;
DROP TABLE GR21_MOV_INTERNO;
DROP TABLE GR21_MOV_SALIDA;
DROP TABLE GR21_PALLET;
DROP TABLE GR21_POSICION;







 


 
 

